# Generated by Django 2.2.3 on 2019-08-10 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_seq', models.IntegerField()),
                ('theme_color', models.TextField()),
                ('theme_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Theme')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_title', models.TextField()),
                ('sche_date', models.DateField()),
                ('sche_content', models.TextField()),
                ('theme_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Sche_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_fromTime', models.TimeField()),
                ('sche_endTime', models.TimeField()),
                ('sche_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cal.Schedule')),
            ],
        ),
    ]
